import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def perform_spatial_clustering(df, n_clusters=3):
    """
    Inspects dataset for geographic coordinates. If absent, performs feature-space analytical
    clustering as an explicit analytical proxy for geographic spatial clustering.
    """
    print("\n" + "="*70)
    print("            SPATIAL CLUSTERING & HOTSPOT ANALYSIS")
    print("="*70)

    # 1. Geographic Coordinate Inspection
    has_lat_lon = 'latitude' in df.columns and 'longitude' in df.columns
    
    if not has_lat_lon:
        print("\n[GEOGRAPHIC COORDINATE AUDIT REPORT]")
        print("  - Status               : Latitude and Longitude columns are ABSENT.")
        print("  - Standard Compliance  : DO NOT fabricate or invent fake GPS coordinates.")
        print("  - Limitation Statement : True geographic spatial clustering (e.g., DBSCAN GPS density)")
        print("                           cannot be performed directly due to dataset specification.")
        print("  - Alternative Approach : Performing Feature-Space Analytical Clustering as a proxy.")
        print("                           (Grouping locations by multidimensional risk profiles).")
        print("-" * 70)

    # 2. Perform Analytical Feature-Space Clustering using scikit-learn KMeans
    cluster_cols = ['total_accidents', 'total_fatalities', 'severity_score', 'average_yearly_accidents']
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df[cluster_cols])

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    df_clustered = df.copy()
    df_clustered['cluster_id'] = kmeans.fit_predict(X_scaled)

    # Profile the clusters
    cluster_profiles = df_clustered.groupby('cluster_id').agg(
        location_count=('sl_no', 'count'),
        mean_accidents=('total_accidents', 'mean'),
        mean_fatalities=('total_fatalities', 'mean'),
        mean_severity=('severity_score', 'mean')
    ).reset_index()

    # Label cluster profiles based on severity
    cluster_profiles = cluster_profiles.sort_values(by='mean_severity', ascending=False).reset_index(drop=True)
    cluster_labels_map = {}
    
    labels_pool = ["Cluster 1: Critical Blackspots (Extreme Severity)", 
                   "Cluster 2: High Fatality / Highway Corridors", 
                   "Cluster 3: Moderate Risk Urban Intersections"]
    
    for i, row in cluster_profiles.iterrows():
        cluster_labels_map[row['cluster_id']] = labels_pool[i]

    df_clustered['cluster_name'] = df_clustered['cluster_id'].map(cluster_labels_map)

    print("\n[ANALYTICAL CLUSTER BREAKDOWN (Scikit-Learn KMeans)]")
    print("-" * 70)
    print(f"{'Cluster Category':<45} | {'Locations':<10} | {'Avg Acc':<8} | {'Avg Fat':<8}")
    print("-" * 70)
    for _, r in cluster_profiles.iterrows():
        c_name = cluster_labels_map[r['cluster_id']]
        print(f"{c_name:<45} | {int(r['location_count']):<10d} | {r['mean_accidents']:<8.1f} | {r['mean_fatalities']:<8.1f}")
    print("-" * 70)

    print("\n[SAMPLE LOCATIONS PER CLUSTER]")
    for cid in range(n_clusters):
        c_rows = df_clustered[df_clustered['cluster_id'] == cid]
        c_title = cluster_labels_map[cid]
        print(f"\n  >>> {c_title} (Total: {len(c_rows)})")
        for idx, (_, r) in enumerate(c_rows.head(3).iterrows(), 1):
            print(f"      {idx}. {r['location_name']} [{r['zone']} Zone] (Acc: {int(r['total_accidents'])}, Fat: {int(r['total_fatalities'])})")
    print("="*70)

    return df_clustered

def view_accident_hotspots(df):
    """
    Displays ranked list of high-risk accident hotspots in terminal.
    """
    print("\n" + "="*80)
    print("                         IDENTIFIED ACCIDENT HOTSPOTS")
    print("="*80)
    print(f"{'Rank':<4} | {'Location Name':<38} | {'Zone':<13} | {'Accidents':<9} | {'Fatalities':<10} | {'Risk':<6}")
    print("-" * 80)
    
    top_spots = df.sort_values(by=['severity_score', 'total_accidents'], ascending=False).reset_index(drop=True)
    
    for rank, row in top_spots.iterrows():
        loc_name = (row['location_name'][:35] + '...') if len(str(row['location_name'])) > 38 else row['location_name']
        print(f"{rank+1:<4d} | {loc_name:<38} | {row['zone']:<13} | {int(row['total_accidents']):<9d} | {int(row['total_fatalities']):<10d} | {row['risk_level']:<6}")
    
    print("-" * 80)
    print("\n[Academic & Legal Disclaimer]")
    print("  * This ranking is generated by machine learning analysis of the supplied dataset.")
    print("  * It is NOT an official government ranking or statutory designation.")
    print("="*80)
